import type { TeamMember } from '../types/TeamMember';
import type { Lead } from '../types/Lead';

export const SEED_TEAM: TeamMember[] = [
  { id: 'u1', name: 'You', color: '#00D4AA' },
  { id: 'u2', name: 'Client Acquisition', color: '#4A9EFF' },
];

export const COLORS = ['#00D4AA', '#4A9EFF', '#FFB547', '#A78BFA', '#F472B6', '#4ADE80', '#FF6B6B', '#FB923C'];

export const SEED_LEADS: Lead[] = [
  { id: 'l1', fname: 'Mati', lname: 'Staniszewski', title: 'Co-Founder', company: 'ElevenLabs', email: 'mati@elevenlabs.io', country: 'UK', stage: 'new', assignee: '', services: ['cyber', 'saas'], notes: 'Scaling AI SaaS — needs data privacy & security', channels: [], created: '2026-06-17' },
  { id: 'l2', fname: 'Sebastian', lname: 'Kielmann', title: 'CTO', company: 'CATCH', email: 'sebastian@catch-talents.de', country: 'Germany', stage: 'new', assignee: '', services: ['saas', 'cyber'], notes: 'EdTech SaaS with GDPR obligations', channels: [], created: '2026-06-17' },
  { id: 'l3', fname: 'Muhammad', lname: 'Iqbal', title: 'CTO', company: 'NGBS', email: 'iqbal@ngbs.co.uk', country: 'UK', stage: 'new', assignee: '', services: ['cyber', 'cloud', 'saas'], notes: 'Cloud/SaaS dev shop — fits all 3 service areas', channels: [], created: '2026-06-17' },
  { id: 'l4', fname: 'Anthony', lname: 'Whyte', title: 'Managing Director', company: 'Talent International', email: 'anthony.whyte@talentinternational.com', country: 'Australia', stage: 'new', assignee: '', services: ['cyber', 'cloud'], notes: 'ISO 27001 certified; Cyber & Cloud/DevOps specialities', channels: [], created: '2026-06-17' },
  { id: 'l5', fname: 'Ryan', lname: 'Milligan', title: 'CRO', company: 'QuotaPath', email: 'ryan.milligan@quotapath.com', country: 'USA', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Growing SaaS with CRM/ERP cloud integrations', channels: [], created: '2026-06-17' },
  { id: 'l6', fname: 'Lycia', lname: 'Lobo', title: 'COO', company: 'Design Museum', email: 'lycia.lobo@designmuseum.org', country: 'UK', stage: 'new', assignee: '', services: ['cyber', 'cloud'], notes: 'Needs cloud modernisation & data protection', channels: [], created: '2026-06-17' },
  { id: 'l7', fname: 'Guy', lname: 'Mason', title: 'Chairman', company: 'TRL', email: 'gmason@trl.co.uk', country: 'UK', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Smart Mobility IoT testbed & traffic mgmt software', channels: [], created: '2026-06-17' },
  { id: 'l8', fname: 'André', lname: 'Witt', title: 'Head of IT', company: 'Dr. Loges + Co.', email: 'witt@loges.de', country: 'Germany', stage: 'new', assignee: '', services: ['cyber', 'cloud'], notes: 'Regulated pharma — secure infra & compliance', channels: [], created: '2026-06-17' },
  { id: 'l9', fname: 'Christopher', lname: 'Franskin', title: 'CIO', company: 'ERGO Insurance', email: 'christopher.franskin@ergo.be', country: 'Belgium', stage: 'new', assignee: '', services: ['cyber', 'cloud'], notes: 'Insurance CIO — cybersecurity & cloud transformation', channels: [], created: '2026-06-17' },
  { id: 'l10', fname: 'Riccardo', lname: 'Picca', title: 'Non-Exec Director', company: 'MIPU Predictive Hub', email: 'riccardo.picca@ext.mipu.eu', country: 'Italy', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Microsoft MIMA winner — IoT cloud & AI SaaS', channels: [], created: '2026-06-17' },
  { id: 'l11', fname: 'Kaul', lname: 'Himanshu', title: 'Co-Founder & CPO', company: 'WooHoo', email: 'himanshu@smartbeings.com', country: 'USA', stage: 'new', assignee: '', services: ['cyber', 'saas'], notes: 'Voice AI with explicit security & encryption focus', channels: [], created: '2026-06-17' },
  { id: 'l12', fname: 'Gabriel', lname: 'Hubert', title: 'Co-Founder', company: 'Dust', email: 'gabriel@dust.tt', country: 'France', stage: 'new', assignee: '', services: ['cyber', 'saas'], notes: 'Enterprise AI — data privacy, access controls & SaaS dev', channels: [], created: '2026-06-17' },
  { id: 'l13', fname: 'Jaime', lname: 'Ramirez', title: 'CIO', company: 'Laboratorios Kener', email: 'jaime.sanchez@kener.com.mx', country: 'Mexico', stage: 'new', assignee: '', services: ['cyber', 'cloud'], notes: 'Pharma CIO — regulatory compliance & cloud infra', channels: [], created: '2026-06-17' },
  { id: 'l14', fname: 'Brett', lname: 'Taylor', title: 'Co-Founder', company: 'Sierra', email: 'bret@sierra.ai', country: 'USA', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Fast-growing conversational AI — cloud & SaaS scaling', channels: [], created: '2026-06-17' },
  { id: 'l15', fname: 'David', lname: 'Higgins', title: 'CTO', company: 'Eftsure', email: 'david@eftsure.com.au', country: 'Australia', stage: 'new', assignee: '', services: ['cyber', 'saas'], notes: 'Cybersecurity IS their product — platform hardening & dev', channels: [], created: '2026-06-17' },
  { id: 'l16', fname: 'Mark', lname: 'Sampford', title: 'Head of Salesforce & CRM', company: 'Square One Resources', email: 'mark.sampford@squareoneresources.com', country: 'UK', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'CRM cloud infra & Salesforce SaaS integrations', channels: [], created: '2026-06-17' },
  { id: 'l17', fname: 'Karim', lname: 'Tarmohamed', title: 'CRO', company: 'Snorkel AI', email: 'karim@snorkel.ai', country: 'USA', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'AI training platform at scale — cloud + SaaS dev', channels: [], created: '2026-06-17' },
  { id: 'l18', fname: 'Mirko', lname: 'Novakovic', title: 'CEO', company: 'Dash0', email: 'mirko.novakovic@dash0.com', country: 'Germany', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Cloud-native observability startup', channels: [], created: '2026-06-17' },
  { id: 'l19', fname: 'Shane', lname: 'Anglin', title: 'SVP Information Security', company: 'Triad Financial Services', email: 'sanglin@triadfs.com', country: 'USA', stage: 'new', assignee: '', services: ['cyber'], notes: 'SVP InfoSec at 47-state financial lender — direct cyber lead', channels: [], created: '2026-06-17' },
  { id: 'l20', fname: 'Shane', lname: 'Anglin', title: 'CISO', company: 'Step Up For Students', email: 'sanglin@stepupforstudents.org', country: 'USA', stage: 'new', assignee: '', services: ['cyber'], notes: 'CISO at nonprofit. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l21', fname: 'Ahmed', lname: 'Rasel', title: 'Co-Founder & Chief Digital Officer', company: 'Musemind UX Design Agency', email: 'rasel.ahmed@musemind.agency', country: 'Germany', stage: 'new', assignee: '', services: ['saas', 'cloud'], notes: 'Global UX design agency. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l22', fname: 'Mike', lname: 'Renwick', title: 'Director of Data and AI', company: 'Lunate', email: 'mrenwick@lunate.com', country: 'UAE', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Director Data & AI, finance firm Abu Dhabi. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l23', fname: 'Demis', lname: 'Hassabis', title: 'Founder & CEO', company: 'Isomorphic Labs', email: 'demis@isomorphiclabs.com', country: 'United Kingdom', stage: 'new', assignee: '', services: ['saas', 'cloud'], notes: 'Founder AI/healthcare lab. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l24', fname: 'Valentin', lname: 'Storz', title: 'Chief Revenue Officer', company: 'Varjo', email: 'valentin.storz@varjo.com', country: 'Germany', stage: 'new', assignee: '', services: ['saas', 'cloud'], notes: 'CRO at XR/VR software company. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l25', fname: 'Max', lname: 'Junestrand', title: 'CEO & Co-Founder', company: 'Legora', email: 'max@leya.law', country: 'USA', stage: 'new', assignee: '', services: ['saas'], notes: 'CEO of legal AI SaaS platform. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l26', fname: 'Paulo', lname: 'De Carvalho Pinto', title: 'Chief Operating Officer', company: 'B&B Hotels', email: 'paulo.pinto@hotel-bb.com', country: 'Portugal', stage: 'new', assignee: '', services: ['cloud', 'cyber'], notes: 'COO hotel chain - cloud & data security. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l27', fname: 'Peter', lname: 'Howells', title: 'VP Australia & New Zealand', company: 'PowerGate Group', email: 'peter.howells@powergatesoftware.com', country: 'Australia', stage: 'new', assignee: '', services: ['saas', 'cloud'], notes: 'VP at tech/software group. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l28', fname: 'Maxime', lname: 'Cohendet', title: 'Co-Founder & Group MD', company: 'Avizio WEFY Group', email: 'maxime@avizio.fr', country: 'France', stage: 'new', assignee: '', services: ['saas'], notes: 'Co-founder recruitment SaaS group. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l29', fname: 'Sanjiv', lname: 'Cherian', title: 'Chief Executive Officer', company: 'Microminder Cyber Security', email: 'sanjiv.cherian@micromindercs.com', country: 'UAE', stage: 'new', assignee: '', services: ['cyber'], notes: 'CEO cybersecurity firm Dubai. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l30', fname: 'Sandrine', lname: 'Pomone', title: 'Chief Executive Officer', company: 'Pomone', email: 'shardel@pomone-sas.fr', country: 'France', stage: 'new', assignee: '', services: ['cloud', 'cyber'], notes: 'CEO manufacturing firm. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l31', fname: 'Delaval', lname: 'Frederic', title: 'Managing Director', company: 'SKYTECH SLP', email: 'frederic.delaval@skytechslp.com', country: 'France', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'MD tech manufacturing. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l32', fname: 'Chris', lname: 'Denbigh White', title: 'Global Head of Cyber Security', company: 'Elwood', email: 'chris.denbigh-white@elwood.io', country: 'United Kingdom', stage: 'new', assignee: '', services: ['cyber'], notes: 'Global Head Cyber Security, finance. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l33', fname: 'David', lname: 'Paffenholz', title: 'CEO & Co-Founder', company: 'Juicebox', email: 'david@juicebox.work', country: 'USA', stage: 'new', assignee: '', services: ['saas', 'cloud'], notes: 'CEO AI people data SaaS. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l34', fname: 'Kosala', lname: 'Indrasiri', title: 'Founder & CEO', company: 'Sanmark Solutions', email: 'kosala@thesanmark.com', country: 'Sri Lanka', stage: 'new', assignee: '', services: ['saas'], notes: 'CEO software dev firm. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l35', fname: 'Clayton', lname: 'Freire', title: 'Director of Technology', company: 'Wine', email: 'claytonfreire@wine.com.br', country: 'Brazil', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Director Technology e-commerce. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
  { id: 'l36', fname: 'Remi', lname: 'Chichery', title: 'Director of IT Omnichannel', company: 'JACQUEMUS', email: 'remi.chichery@jacquemus.com', country: 'France', stage: 'new', assignee: '', services: ['cloud', 'saas'], notes: 'Director IT luxury fashion brand. Lusha 18 Jun 2026.', channels: [], created: '2026-06-18' },
];
